// Mcp3428::Mcp3428
// Filename: ConversionResult.cs
// Created: __
// Edited: 20190405
// Creator: Máté Kullai

using System;

namespace Iot.Device.Mcp3428
{
    public interface IAdcResult
    {
        byte Channel { get; }
        double Voltage { get; }
    }

    public delegate void ConversionResultHandler(object sender, ConversionResult e);

    public readonly struct ConversionResult : IAdcResult
    {
        public ConversionResult(byte channel, short rawData, ResolutionEnum resolution)
        {
            Channel = channel;
            RawData = rawData;
            Resolution = resolution;
        }

        /// <summary>
        /// Gets the channel.
        /// </summary>
        /// <value>The channel.</value>
        /// <autogeneratedoc />
        public byte Channel { get; }

        /// <summary>
        /// Gets the raw data.
        /// </summary>
        /// <value>The raw data.</value>
        /// <autogeneratedoc />
        public Int16 RawData { get; }

        /// <summary>
        /// Gets the resolution.
        /// </summary>
        /// <value>The resolution.</value>
        /// <autogeneratedoc />
        private ResolutionEnum Resolution { get; }

        public double LSBValue => Helpers.LSBValue(Resolution);

        /// <summary>
        /// Gets the voltage.
        /// </summary>
        /// <value>The voltage.</value>
        /// <autogeneratedoc />
        public double Voltage => Helpers.LSBValue(Resolution) * RawData;
    }
}
