// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;

namespace Iot.Device.Mcp3428
{
    public readonly struct ConversionResult
    {
        public ConversionResult(byte channel, short rawData, ResolutionEnum resolution)
        {
            Channel = channel;
            RawData = rawData;
            Resolution = resolution;
        }

        /// <summary>
        /// Gets the channel.
        /// </summary>
        /// <value>The channel.</value>
        /// <autogeneratedoc />
        public byte Channel { get; }

        /// <summary>
        /// Gets the raw data.
        /// </summary>
        /// <value>The raw data.</value>
        /// <autogeneratedoc />
        public short RawData { get; }

        /// <summary>
        /// Gets the resolution.
        /// </summary>
        /// <value>The resolution.</value>
        /// <autogeneratedoc />
        private ResolutionEnum Resolution { get; }

        /// <summary>
        /// Voltage value of the least significant bit of the data
        /// </summary>
        /// <value>The LSB value.</value>
        /// <autogeneratedoc />
        public double LsbValue => Helpers.LSBValue(Resolution);

        /// <summary>
        /// Gets the voltage.
        /// </summary>
        /// <value>The voltage.</value>
        /// <autogeneratedoc />
        public double Voltage => LsbValue * RawData;
    }
}
