#pragma warning disable CS1591

namespace Iot.Device.Arduino
{
    public enum ArduinoImplementation
    {
        None = 0,
        SetPinMode,
        WritePin,
        ReadPin,
        EnvironmentTickCount,
        SleepMicroseconds,
        GetMicroseconds,
        Debug,
        ObjectEquals,
        ReferenceEquals,
        GetType,
        GetHashCode,
        ArrayCopy5,
        StringCtor0,
        StringLength,
        MonitorEnter1,
        MonitorEnter2,
        MonitorExit,
        StringIndexer,
        StringFormat2,
        StringFormat2b,
        BaseTypeEquals,
        EmptyStaticCtor,
        DefaultEqualityComparer,
        ArrayCopy3,
        StringFormat3,
        ArrayClone,
        GetPinMode,
        IsPinModeSupported,
        GetPinCount,
        RuntimeHelpersInitializeArray,
        RuntimeHelpersRunClassConstructor,
        TypeGetTypeFromHandle,
        BaseGetHashCode,
        FailFast1,
        FailFast2,

        TypeOp_Equality,
        TypeOp_Inequality,
        TypeEquals,
        TypeIsAssignableTo,
        TypeIsEnum,
        TypeTypeHandle,
        TypeIsValueType,
        TypeIsSubclassOf,
        TypeIsAssignableFrom,
        TypeCtor,
        ObjectReferenceEquals,
        TypeMakeGenericType
    }
}
