using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using ArduinoCsCompiler;
using Iot.Device.Arduino;
using Iot.Device.Board;
using Xunit;
using SystemException = ArduinoCsCompiler.SystemException;

namespace Iot.Device.Arduino.Tests
{
    /// <summary>
    /// This class is used to copy some information to the Arduino code, so that it stays in sync with the C# part
    /// </summary>
    public partial class WriteRuntimeCoreData
    {
        /// <summary>
        /// Returns the path where the runtime sources are
        /// </summary>
        /// <returns></returns>
        private string GetRuntimePath()
        {
            string path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            return Path.Combine(path, @"Arduino\ExtendedConfigurableFirmata");
        }

        [Fact]
        public void WriteNativeMethodDefinitions()
        {
            // WriteEnumHeaderFile<NativeMethod>();
            // Collect all methods that have an ArduinoImplementation attribute attached to them.
            // Must scan all functions, including internals.
            Assembly[] typesWhereToLook = new Assembly[]
            {
                Assembly.GetAssembly(typeof(MicroCompiler))!,
                Assembly.GetAssembly(typeof(ArduinoBoard))!
            };

            string[] specials = new string[]
            {
                "ByReferenceCtor",
                "ByReferenceValue",
            };

            Dictionary<string, int> entries = new();

            foreach (var s in specials)
            {
                entries.Add(s, ArduinoImplementationAttribute.GetStaticHashCode(s));
            }

            // The loop below will throw on duplicate entries. This is expected.
            foreach (var a in typesWhereToLook)
            {
                foreach (var type in a.GetTypes())
                {
                    foreach (var method in type.GetMethods(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public))
                    {
                        var attribs = method.GetCustomAttributes(typeof(ArduinoImplementationAttribute)).Cast<ArduinoImplementationAttribute>();
                        var attrib = attribs.FirstOrDefault();
                        if (attrib != null && attrib.MethodNumber != 0)
                        {
                            TryAddEntry(entries, attrib);
                        }
                    }

                    foreach (var method in type.GetConstructors(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public))
                    {
                        var attribs = method.GetCustomAttributes(typeof(ArduinoImplementationAttribute)).Cast<ArduinoImplementationAttribute>();
                        var attrib = attribs.FirstOrDefault();
                        if (attrib != null && attrib.MethodNumber != 0)
                        {
                            TryAddEntry(entries, attrib);
                        }
                    }
                }
            }

            var hashCodes = entries.Select(x => x.Value).ToList();
            IEnumerable<int> duplicates = entries.GroupBy(x => x.Value)
                .Where(g => g.Count() > 1)
                .Select(x => x.Key).ToList();
            if (duplicates.Any())
            {
                throw new InvalidOperationException($"Duplicate method keys found: {duplicates.First()}");
            }

            var list = entries.OrderBy(x => x.Key).Select(y => (y.Key, y.Value));
            var reverseLookupList = entries.OrderBy(x => x.Value).Select(y => (y.Value, y.Key));
            WriteNativeMethodList(list, reverseLookupList);
        }

        private void TryAddEntry(Dictionary<string, int> entries, ArduinoImplementationAttribute attrib)
        {
            if (!entries.ContainsKey(attrib.Name))
            {
                entries.Add(attrib.Name, attrib.MethodNumber);
            }
            else if (entries[attrib.Name] == attrib.MethodNumber)
            {
                // Nothing to do
            }
            else
            {
                throw new InvalidOperationException($"Method {attrib.Name} was already declared with a different hash code");
            }
        }

        private void WriteNativeMethodList(IEnumerable<(string Key, int Value)> entries, IEnumerable<(int Value, string Key)> reverseLookupList)
        {
            string name = "NativeMethod";
            string header = FormattableString.Invariant($@"
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
// Native method numbers, ordered by method name
enum class {name}
{{
    None = 0,
");
            string outputFile = Path.Combine(GetRuntimePath(), name + ".h");
            TextWriter w = new StreamWriter(outputFile, false, Encoding.ASCII);
            w.Write(header);
            foreach (var e in entries)
            {
                w.WriteLine(FormattableString.Invariant($"    {e.Key} = {e.Value},"));
            }

            w.WriteLine("};"); // Tail

            w.WriteLine("/* Reverse lookup list (ordered by value)");
            foreach (var e in reverseLookupList)
            {
                w.WriteLine($"{e.Value} (0x{e.Value:X}) -> {e.Key}");
            }

            w.WriteLine("*/");
            w.Close();
        }

        [Fact]
        public void WriteSystemExceptions()
        {
            WriteEnumHeaderFile<SystemException>();
        }

        [Fact]
        public void WriteMethodFlags()
        {
            WriteEnumHeaderFile<MethodFlags>();
        }

        [Fact]
        public void WriteKnownTypeTokens()
        {
            WriteEnumHeaderFile<KnownTypeTokens>();
        }

        [Fact]
        public void WriteExceptionClauseTypes()
        {
            WriteEnumHeaderFile<ExceptionHandlingClauseOptions>();
        }

        [Fact]
        public void WriteRuntimeState()
        {
            WriteEnumHeaderFile<RuntimeState>();
        }

        [Fact]
        public void WriteDebuggerCommands()
        {
            WriteEnumHeaderFile<DebuggerCommand>();
        }

        [Fact]
        public void WriteBreakpointTypes()
        {
            WriteEnumHeaderFile<BreakpointType>();
        }

        [Fact]
        public void WritePinUsage()
        {
            WriteEnumHeaderFile<PinUsage>();
        }

        [Fact]
        public void WriteExecutorCommands()
        {
            string name = nameof(ExecutorCommand);
            string header = FormattableString.Invariant($@"
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class {name}
{{
");
            string outputFile = Path.Combine(GetRuntimePath(), name + ".h");
            TextWriter w = new StreamWriter(outputFile, false, Encoding.ASCII);
            w.Write(header);
            foreach (var e in Enum.GetValues(typeof(ExecutorCommand)))
            {
                w.WriteLine(FormattableString.Invariant($"    {e.ToString()} = {(byte)e},"));
            }

            w.WriteLine("};"); // Tail
            w.Close();
        }

        [Fact]
        public void WriteVariableKind()
        {
            string name = nameof(VariableKind);
            string header = FormattableString.Invariant($@"
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class {name}
{{
");
            string outputFile = Path.Combine(GetRuntimePath(), name + ".h");
            TextWriter w = new StreamWriter(outputFile, false, Encoding.ASCII);
            w.Write(header);
            foreach (var e in Enum.GetValues(typeof(VariableKind)))
            {
                w.WriteLine(FormattableString.Invariant($"    {e.ToString()} = {(byte)e},"));
            }

            w.WriteLine("};"); // Tail
            w.Close();
        }

        private void WriteEnumHeaderFile<T>()
            where T : Enum
        {
            string name = typeof(T).Name;
            string header = FormattableString.Invariant($@"
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class {name}
{{
");
            string outputFile = Path.Combine(GetRuntimePath(), name + ".h");
            // Must use ascii encoding, because GCC fails to recognize the UTF-8-BOM header
            // sometimes. Not sure why it works sometimes only.
            TextWriter w = new StreamWriter(outputFile, false, Encoding.ASCII);
            w.Write(header);
            foreach (var e in Enum.GetValues(typeof(T)))
            {
                w.WriteLine(FormattableString.Invariant($"    {e.ToString()} = {(int)e},"));
            }

            w.WriteLine("};"); // Tail
            w.Close();
        }
    }
}
