// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Generic;

namespace Iot.Device.Card.CreditCardProcessing
{
    public class WorldCountryCurrency
    {
        /// <summary>
        /// List of countries, currency names, currency codes, currency code number and country code number
        /// Use this list to display a country name when extracting the currency or country code names from the card
        /// </summary>
        public static List<CountryCurrency> CountryCurrencies = new List<CountryCurrency>()
        {
            new CountryCurrency() { Country = "Afghanistan", CurrencyName = "Afghani", CurrencyCode = "AFN", CurrencyNumber = 971, CountryNumber = 4 },
            new CountryCurrency() { Country = "Albania", CurrencyName = "Lek", CurrencyCode = "ALL", CurrencyNumber = 8, CountryNumber = 8 },
            new CountryCurrency() { Country = "Algeria", CurrencyName = "Algerian Dinar", CurrencyCode = "DZD", CurrencyNumber = 12, CountryNumber = 12 },
            new CountryCurrency() { Country = "American Samoa", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 16 },
            new CountryCurrency() { Country = "Andorra", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 20 },
            new CountryCurrency() { Country = "Angola", CurrencyName = "Kwanza", CurrencyCode = "AOA", CurrencyNumber = 973, CountryNumber = 24 },
            new CountryCurrency() { Country = "Anguilla", CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", CurrencyNumber = 951, CountryNumber = 660 },
            new CountryCurrency() { Country = "Antigua And Barbuda", CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", CurrencyNumber = 951, CountryNumber = 28 },
            new CountryCurrency() { Country = "Argentina", CurrencyName = "Argentine Peso", CurrencyCode = "ARS", CurrencyNumber = 32, CountryNumber = 32 },
            new CountryCurrency() { Country = "Armenia", CurrencyName = "Armenian Dram", CurrencyCode = "AMD", CurrencyNumber = 51, CountryNumber = 51 },
            new CountryCurrency() { Country = "Aruba", CurrencyName = "Aruban Florin", CurrencyCode = "AWG", CurrencyNumber = 533, CountryNumber = 533 },
            new CountryCurrency() { Country = "Australia", CurrencyName = "Australian Dollar", CurrencyCode = "AUD", CurrencyNumber = 36, CountryNumber = 36 },
            new CountryCurrency() { Country = "Austria", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 40 },
            new CountryCurrency() { Country = "Azerbaijan", CurrencyName = "Azerbaijanian Manat", CurrencyCode = "AZN", CurrencyNumber = 944, CountryNumber = 31 },
            new CountryCurrency() { Country = "Bahamas (The)", CurrencyName = "Bahamian Dollar", CurrencyCode = "BSD", CurrencyNumber = 44, CountryNumber = 44 },
            new CountryCurrency() { Country = "Bahrain", CurrencyName = "Bahraini Dinar", CurrencyCode = "BHD", CurrencyNumber = 48, CountryNumber = 48 },
            new CountryCurrency() { Country = "Bangladesh", CurrencyName = "Taka", CurrencyCode = "BDT", CurrencyNumber = 50, CountryNumber = 50 },
            new CountryCurrency() { Country = "Barbados", CurrencyName = "Barbados Dollar", CurrencyCode = "BBD", CurrencyNumber = 52, CountryNumber = 52 },
            new CountryCurrency() { Country = "Belarus", CurrencyName = "Belarussian Ruble", CurrencyCode = "BYN", CurrencyNumber = 933, CountryNumber = 112 },
            new CountryCurrency() { Country = "Belgium", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 56 },
            new CountryCurrency() { Country = "Belize", CurrencyName = "Belize Dollar", CurrencyCode = "BZD", CurrencyNumber = 84, CountryNumber = 84 },
            new CountryCurrency() { Country = "Benin", CurrencyName = "CFA Franc BCEAO", CurrencyCode = "XOF", CurrencyNumber = 952, CountryNumber = 204 },
            new CountryCurrency() { Country = "Bermuda", CurrencyName = "Bermudian Dollar", CurrencyCode = "BMD", CurrencyNumber = 60, CountryNumber = 60 },
            new CountryCurrency() { Country = "Bhutan", CurrencyName = "Ngultrum", CurrencyCode = "BTN", CurrencyNumber = 64, CountryNumber = 64 },
            new CountryCurrency() { Country = "Bhutan", CurrencyName = "Indian Rupee", CurrencyCode = "INR", CurrencyNumber = 356, CountryNumber = 64 },
            new CountryCurrency() { Country = "Bolivia (Plurinational State Of)", CurrencyName = "Boliviano", CurrencyCode = "BOB", CurrencyNumber = 68, CountryNumber = 68 },
            new CountryCurrency() { Country = "Bolivia (Plurinational State Of)", CurrencyName = "Mvdol", CurrencyCode = "BOV", CurrencyNumber = 984, CountryNumber = 68 },
            new CountryCurrency() { Country = "Bonaire, Sint Eustatius And Saba", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 535 },
            new CountryCurrency() { Country = "Bosnia And Herzegovina", CurrencyName = "Convertible Mark", CurrencyCode = "BAM", CurrencyNumber = 977, CountryNumber = 70 },
            new CountryCurrency() { Country = "Botswana", CurrencyName = "Pula", CurrencyCode = "BWP", CurrencyNumber = 72, CountryNumber = 72 },
            new CountryCurrency() { Country = "Bouvet Island", CurrencyName = "Norwegian Krone", CurrencyCode = "NOK", CurrencyNumber = 578, CountryNumber = 74 },
            new CountryCurrency() { Country = "Brazil", CurrencyName = "Brazilian Real", CurrencyCode = "BRL", CurrencyNumber = 986, CountryNumber = 76 },
            new CountryCurrency() { Country = "British Indian Ocean Territory (The)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 86 },
            new CountryCurrency() { Country = "Brunei Darussalam", CurrencyName = "Brunei Dollar", CurrencyCode = "BND", CurrencyNumber = 96, CountryNumber = 96 },
            new CountryCurrency() { Country = "Bulgaria", CurrencyName = "Bulgarian Lev", CurrencyCode = "BGN", CurrencyNumber = 975, CountryNumber = 100 },
            new CountryCurrency() { Country = "Burkina Faso", CurrencyName = "CFA Franc BCEAO", CurrencyCode = "XOF", CurrencyNumber = 952, CountryNumber = 854 },
            new CountryCurrency() { Country = "Burundi", CurrencyName = "Burundi Franc", CurrencyCode = "BIF", CurrencyNumber = 108, CountryNumber = 108 },
            new CountryCurrency() { Country = "Cabo Verde", CurrencyName = "Cabo Verde Escudo", CurrencyCode = "CVE", CurrencyNumber = 132, CountryNumber = 132 },
            new CountryCurrency() { Country = "Cambodia", CurrencyName = "Riel", CurrencyCode = "KHR", CurrencyNumber = 116, CountryNumber = 116 },
            new CountryCurrency() { Country = "Cameroon", CurrencyName = "CFA Franc BEAC", CurrencyCode = "XAF", CurrencyNumber = 950, CountryNumber = 120 },
            new CountryCurrency() { Country = "Canada", CurrencyName = "Canadian Dollar", CurrencyCode = "CAD", CurrencyNumber = 124, CountryNumber = 124 },
            new CountryCurrency() { Country = "Cayman Islands (The)", CurrencyName = "Cayman Islands Dollar", CurrencyCode = "KYD", CurrencyNumber = 136, CountryNumber = 136 },
            new CountryCurrency() { Country = "Central African Republic (The)", CurrencyName = "CFA Franc BEAC", CurrencyCode = "XAF", CurrencyNumber = 950, CountryNumber = 140 },
            new CountryCurrency() { Country = "Chad", CurrencyName = "CFA Franc BEAC", CurrencyCode = "XAF", CurrencyNumber = 950, CountryNumber = 148 },
            new CountryCurrency() { Country = "Chile", CurrencyName = "Unidad de Fomento", CurrencyCode = "CLF", CurrencyNumber = 990, CountryNumber = 152 },
            new CountryCurrency() { Country = "Chile", CurrencyName = "Chilean Peso", CurrencyCode = "CLP", CurrencyNumber = 152, CountryNumber = 152 },
            new CountryCurrency() { Country = "China", CurrencyName = "Yuan Renminbi", CurrencyCode = "CNY", CurrencyNumber = 156, CountryNumber = 156 },
            new CountryCurrency() { Country = "Christmas Island", CurrencyName = "Australian Dollar", CurrencyCode = "AUD", CurrencyNumber = 36, CountryNumber = 162 },
            new CountryCurrency() { Country = "Cocos (Keeling) Islands (The)", CurrencyName = "Australian Dollar", CurrencyCode = "AUD", CurrencyNumber = 36, CountryNumber = 166 },
            new CountryCurrency() { Country = "Colombia", CurrencyName = "Colombian Peso", CurrencyCode = "COP", CurrencyNumber = 170, CountryNumber = 170 },
            new CountryCurrency() { Country = "Colombia", CurrencyName = "Unidad de Valor Real", CurrencyCode = "COU", CurrencyNumber = 970, CountryNumber = 170 },
            new CountryCurrency() { Country = "Comoros (The)", CurrencyName = "Comoro Franc", CurrencyCode = "KMF", CurrencyNumber = 174, CountryNumber = 174 },
            new CountryCurrency() { Country = "Congo (The Democratic Republic Of The)", CurrencyName = "Congolese Franc", CurrencyCode = "CDF", CurrencyNumber = 976, CountryNumber = 180 },
            new CountryCurrency() { Country = "Congo (The)", CurrencyName = "CFA Franc BEAC", CurrencyCode = "XAF", CurrencyNumber = 950, CountryNumber = 178 },
            new CountryCurrency() { Country = "Cook Islands (The)", CurrencyName = "New Zealand Dollar", CurrencyCode = "NZD", CurrencyNumber = 554, CountryNumber = 184 },
            new CountryCurrency() { Country = "Costa Rica", CurrencyName = "Costa Rican Colon", CurrencyCode = "CRC", CurrencyNumber = 188, CountryNumber = 188 },
            new CountryCurrency() { Country = "Croatia", CurrencyName = "Kuna", CurrencyCode = "HRK", CurrencyNumber = 191, CountryNumber = 191 },
            new CountryCurrency() { Country = "Cuba", CurrencyName = "Peso Convertible", CurrencyCode = "CUC", CurrencyNumber = 931, CountryNumber = 192 },
            new CountryCurrency() { Country = "Cuba", CurrencyName = "Cuban Peso", CurrencyCode = "CUP", CurrencyNumber = 192, CountryNumber = 192 },
            new CountryCurrency() { Country = "Curaçao", CurrencyName = "Netherlands Antillean Guilder", CurrencyCode = "ANG", CurrencyNumber = 532, CountryNumber = 531 },
            new CountryCurrency() { Country = "Cyprus", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 196 },
            new CountryCurrency() { Country = "Czech Republic (The)", CurrencyName = "Czech Koruna", CurrencyCode = "CZK", CurrencyNumber = 203, CountryNumber = 203 },
            new CountryCurrency() { Country = "Côte D'Ivoire", CurrencyName = "CFA Franc BCEAO", CurrencyCode = "XOF", CurrencyNumber = 952, CountryNumber = 384 },
            new CountryCurrency() { Country = "Denmark", CurrencyName = "Danish Krone", CurrencyCode = "DKK", CurrencyNumber = 208, CountryNumber = 208 },
            new CountryCurrency() { Country = "Djibouti", CurrencyName = "Djibouti Franc", CurrencyCode = "DJF", CurrencyNumber = 262, CountryNumber = 262 },
            new CountryCurrency() { Country = "Dominica", CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", CurrencyNumber = 951, CountryNumber = 212 },
            new CountryCurrency() { Country = "Dominican Republic (The)", CurrencyName = "Dominican Peso", CurrencyCode = "DOP", CurrencyNumber = 214, CountryNumber = 214 },
            new CountryCurrency() { Country = "Ecuador", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 218 },
            new CountryCurrency() { Country = "Egypt", CurrencyName = "Egyptian Pound", CurrencyCode = "EGP", CurrencyNumber = 818, CountryNumber = 818 },
            new CountryCurrency() { Country = "El Salvador", CurrencyName = "El Salvador Colon", CurrencyCode = "SVC", CurrencyNumber = 222, CountryNumber = 222 },
            new CountryCurrency() { Country = "El Salvador", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 222 },
            new CountryCurrency() { Country = "Equatorial Guinea", CurrencyName = "CFA Franc BEAC", CurrencyCode = "XAF", CurrencyNumber = 950, CountryNumber = 226 },
            new CountryCurrency() { Country = "Eritrea", CurrencyName = "Nakfa", CurrencyCode = "ERN", CurrencyNumber = 232, CountryNumber = 232 },
            new CountryCurrency() { Country = "Estonia", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 233 },
            new CountryCurrency() { Country = "Ethiopia", CurrencyName = "Ethiopian Birr", CurrencyCode = "ETB", CurrencyNumber = 230, CountryNumber = 231 },
            new CountryCurrency() { Country = "European Union", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 0 },
            new CountryCurrency() { Country = "Falkland Islands (The) [Malvinas]", CurrencyName = "Falkland Islands Pound", CurrencyCode = "FKP", CurrencyNumber = 238, CountryNumber = 238 },
            new CountryCurrency() { Country = "Faroe Islands (The)", CurrencyName = "Danish Krone", CurrencyCode = "DKK", CurrencyNumber = 208, CountryNumber = 234 },
            new CountryCurrency() { Country = "Fiji", CurrencyName = "Fiji Dollar", CurrencyCode = "FJD", CurrencyNumber = 242, CountryNumber = 242 },
            new CountryCurrency() { Country = "Finland", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 246 },
            new CountryCurrency() { Country = "France", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 250 },
            new CountryCurrency() { Country = "French Guiana", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 254 },
            new CountryCurrency() { Country = "French Polynesia", CurrencyName = "CFP Franc", CurrencyCode = "XPF", CurrencyNumber = 953, CountryNumber = 258 },
            new CountryCurrency() { Country = "French Southern Territories (The)", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 260 },
            new CountryCurrency() { Country = "Gabon", CurrencyName = "CFA Franc BEAC", CurrencyCode = "XAF", CurrencyNumber = 950, CountryNumber = 266 },
            new CountryCurrency() { Country = "Gambia (The)", CurrencyName = "Dalasi", CurrencyCode = "GMD", CurrencyNumber = 270, CountryNumber = 270 },
            new CountryCurrency() { Country = "Georgia", CurrencyName = "Lari", CurrencyCode = "GEL", CurrencyNumber = 981, CountryNumber = 268 },
            new CountryCurrency() { Country = "Germany", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 276 },
            new CountryCurrency() { Country = "Ghana", CurrencyName = "Ghana Cedi", CurrencyCode = "GHS", CurrencyNumber = 936, CountryNumber = 288 },
            new CountryCurrency() { Country = "Gibraltar", CurrencyName = "Gibraltar Pound", CurrencyCode = "GIP", CurrencyNumber = 292, CountryNumber = 292 },
            new CountryCurrency() { Country = "Greece", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 300 },
            new CountryCurrency() { Country = "Greenland", CurrencyName = "Danish Krone", CurrencyCode = "DKK", CurrencyNumber = 208, CountryNumber = 304 },
            new CountryCurrency() { Country = "Grenada", CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", CurrencyNumber = 951, CountryNumber = 308 },
            new CountryCurrency() { Country = "Guadeloupe", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 312 },
            new CountryCurrency() { Country = "Guam", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 316 },
            new CountryCurrency() { Country = "Guatemala", CurrencyName = "Quetzal", CurrencyCode = "GTQ", CurrencyNumber = 320, CountryNumber = 320 },
            new CountryCurrency() { Country = "Guernsey", CurrencyName = "Pound Sterling", CurrencyCode = "GBP", CurrencyNumber = 826, CountryNumber = 831 },
            new CountryCurrency() { Country = "Guinea", CurrencyName = "Guinea Franc", CurrencyCode = "GNF", CurrencyNumber = 324, CountryNumber = 324 },
            new CountryCurrency() { Country = "Guinea-Bissau", CurrencyName = "CFA Franc BCEAO", CurrencyCode = "XOF", CurrencyNumber = 952, CountryNumber = 624 },
            new CountryCurrency() { Country = "Guyana", CurrencyName = "Guyana Dollar", CurrencyCode = "GYD", CurrencyNumber = 328, CountryNumber = 328 },
            new CountryCurrency() { Country = "Haiti", CurrencyName = "Gourde", CurrencyCode = "HTG", CurrencyNumber = 332, CountryNumber = 332 },
            new CountryCurrency() { Country = "Haiti", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 332 },
            new CountryCurrency() { Country = "Heard Island And Mcdonald Islands", CurrencyName = "Australian Dollar", CurrencyCode = "AUD", CurrencyNumber = 36, CountryNumber = 334 },
            new CountryCurrency() { Country = "Holy See (The)", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 336 },
            new CountryCurrency() { Country = "Honduras", CurrencyName = "Lempira", CurrencyCode = "HNL", CurrencyNumber = 340, CountryNumber = 340 },
            new CountryCurrency() { Country = "Hong Kong", CurrencyName = "Hong Kong Dollar", CurrencyCode = "HKD", CurrencyNumber = 344, CountryNumber = 344 },
            new CountryCurrency() { Country = "Hungary", CurrencyName = "Forint", CurrencyCode = "HUF", CurrencyNumber = 348, CountryNumber = 348 },
            new CountryCurrency() { Country = "Iceland", CurrencyName = "Iceland Krona", CurrencyCode = "ISK", CurrencyNumber = 352, CountryNumber = 352 },
            new CountryCurrency() { Country = "India", CurrencyName = "Indian Rupee", CurrencyCode = "INR", CurrencyNumber = 356, CountryNumber = 356 },
            new CountryCurrency() { Country = "Indonesia", CurrencyName = "Rupiah", CurrencyCode = "IDR", CurrencyNumber = 360, CountryNumber = 360 },
            new CountryCurrency() { Country = "International Monetary Fund (Imf) ", CurrencyName = "SDR (Special Drawing Right)", CurrencyCode = "XDR", CurrencyNumber = 960, CountryNumber = 0 },
            new CountryCurrency() { Country = "Iran (Islamic Republic Of)", CurrencyName = "Iranian Rial", CurrencyCode = "IRR", CurrencyNumber = 364, CountryNumber = 364 },
            new CountryCurrency() { Country = "Iraq", CurrencyName = "Iraqi Dinar", CurrencyCode = "IQD", CurrencyNumber = 368, CountryNumber = 368 },
            new CountryCurrency() { Country = "Ireland", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 372 },
            new CountryCurrency() { Country = "Isle Of Man", CurrencyName = "Pound Sterling", CurrencyCode = "GBP", CurrencyNumber = 826, CountryNumber = 833 },
            new CountryCurrency() { Country = "Israel", CurrencyName = "New Israeli Sheqel", CurrencyCode = "ILS", CurrencyNumber = 376, CountryNumber = 376 },
            new CountryCurrency() { Country = "Italy", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 380 },
            new CountryCurrency() { Country = "Jamaica", CurrencyName = "Jamaican Dollar", CurrencyCode = "JMD", CurrencyNumber = 388, CountryNumber = 388 },
            new CountryCurrency() { Country = "Japan", CurrencyName = "Yen", CurrencyCode = "JPY", CurrencyNumber = 392, CountryNumber = 392 },
            new CountryCurrency() { Country = "Jersey", CurrencyName = "Pound Sterling", CurrencyCode = "GBP", CurrencyNumber = 826, CountryNumber = 832 },
            new CountryCurrency() { Country = "Jordan", CurrencyName = "Jordanian Dinar", CurrencyCode = "JOD", CurrencyNumber = 400, CountryNumber = 400 },
            new CountryCurrency() { Country = "Kazakhstan", CurrencyName = "Tenge", CurrencyCode = "KZT", CurrencyNumber = 398, CountryNumber = 398 },
            new CountryCurrency() { Country = "Kenya", CurrencyName = "Kenyan Shilling", CurrencyCode = "KES", CurrencyNumber = 404, CountryNumber = 404 },
            new CountryCurrency() { Country = "Kiribati", CurrencyName = "Australian Dollar", CurrencyCode = "AUD", CurrencyNumber = 36, CountryNumber = 296 },
            new CountryCurrency() { Country = "Korea (The Democratic People’S Republic Of)", CurrencyName = "North Korean Won", CurrencyCode = "KPW", CurrencyNumber = 408, CountryNumber = 408 },
            new CountryCurrency() { Country = "Korea (The Republic Of)", CurrencyName = "Won", CurrencyCode = "KRW", CurrencyNumber = 410, CountryNumber = 410 },
            new CountryCurrency() { Country = "Kuwait", CurrencyName = "Kuwaiti Dinar", CurrencyCode = "KWD", CurrencyNumber = 414, CountryNumber = 414 },
            new CountryCurrency() { Country = "Kyrgyzstan", CurrencyName = "Som", CurrencyCode = "KGS", CurrencyNumber = 417, CountryNumber = 417 },
            new CountryCurrency() { Country = "Lao People’S Democratic Republic (The)", CurrencyName = "Kip", CurrencyCode = "LAK", CurrencyNumber = 418, CountryNumber = 418 },
            new CountryCurrency() { Country = "Latvia", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 428 },
            new CountryCurrency() { Country = "Lebanon", CurrencyName = "Lebanese Pound", CurrencyCode = "LBP", CurrencyNumber = 422, CountryNumber = 422 },
            new CountryCurrency() { Country = "Lesotho", CurrencyName = "Loti", CurrencyCode = "LSL", CurrencyNumber = 426, CountryNumber = 426 },
            new CountryCurrency() { Country = "Lesotho", CurrencyName = "Rand", CurrencyCode = "ZAR", CurrencyNumber = 710, CountryNumber = 426 },
            new CountryCurrency() { Country = "Liberia", CurrencyName = "Liberian Dollar", CurrencyCode = "LRD", CurrencyNumber = 430, CountryNumber = 430 },
            new CountryCurrency() { Country = "Libya", CurrencyName = "Libyan Dinar", CurrencyCode = "LYD", CurrencyNumber = 434, CountryNumber = 434 },
            new CountryCurrency() { Country = "Liechtenstein", CurrencyName = "Swiss Franc", CurrencyCode = "CHF", CurrencyNumber = 756, CountryNumber = 438 },
            new CountryCurrency() { Country = "Lithuania", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 440 },
            new CountryCurrency() { Country = "Luxembourg", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 442 },
            new CountryCurrency() { Country = "Macao", CurrencyName = "Pataca", CurrencyCode = "MOP", CurrencyNumber = 446, CountryNumber = 446 },
            new CountryCurrency() { Country = "Madagascar", CurrencyName = "Malagasy Ariary", CurrencyCode = "MGA", CurrencyNumber = 969, CountryNumber = 450 },
            new CountryCurrency() { Country = "Malawi", CurrencyName = "Kwacha", CurrencyCode = "MWK", CurrencyNumber = 454, CountryNumber = 454 },
            new CountryCurrency() { Country = "Malaysia", CurrencyName = "Malaysian Ringgit", CurrencyCode = "MYR", CurrencyNumber = 458, CountryNumber = 458 },
            new CountryCurrency() { Country = "Maldives", CurrencyName = "Rufiyaa", CurrencyCode = "MVR", CurrencyNumber = 462, CountryNumber = 462 },
            new CountryCurrency() { Country = "Mali", CurrencyName = "CFA Franc BCEAO", CurrencyCode = "XOF", CurrencyNumber = 952, CountryNumber = 466 },
            new CountryCurrency() { Country = "Malta", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 470 },
            new CountryCurrency() { Country = "Marshall Islands (The)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 584 },
            new CountryCurrency() { Country = "Martinique", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 474 },
            new CountryCurrency() { Country = "Mauritania", CurrencyName = "Ouguiya", CurrencyCode = "MRU", CurrencyNumber = 929, CountryNumber = 478 },
            new CountryCurrency() { Country = "Mauritius", CurrencyName = "Mauritius Rupee", CurrencyCode = "MUR", CurrencyNumber = 480, CountryNumber = 480 },
            new CountryCurrency() { Country = "Mayotte", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 175 },
            new CountryCurrency() { Country = "Member Countries Of The African Development Bank Group", CurrencyName = "ADB Unit of Account", CurrencyCode = "XUA", CurrencyNumber = 965, CountryNumber = 0 },
            new CountryCurrency() { Country = "Mexico", CurrencyName = "Mexican Peso", CurrencyCode = "MXN", CurrencyNumber = 484, CountryNumber = 484 },
            new CountryCurrency() { Country = "Mexico", CurrencyName = "Mexican Unidad de Inversion (UDI)", CurrencyCode = "MXV", CurrencyNumber = 979, CountryNumber = 484 },
            new CountryCurrency() { Country = "Micronesia (Federated States Of)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 583 },
            new CountryCurrency() { Country = "Moldova (The Republic Of)", CurrencyName = "Moldovan Leu", CurrencyCode = "MDL", CurrencyNumber = 498, CountryNumber = 498 },
            new CountryCurrency() { Country = "Monaco", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 492 },
            new CountryCurrency() { Country = "Mongolia", CurrencyName = "Tugrik", CurrencyCode = "MNT", CurrencyNumber = 496, CountryNumber = 496 },
            new CountryCurrency() { Country = "Montenegro", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 499 },
            new CountryCurrency() { Country = "Montserrat", CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", CurrencyNumber = 951, CountryNumber = 500 },
            new CountryCurrency() { Country = "Morocco", CurrencyName = "Moroccan Dirham", CurrencyCode = "MAD", CurrencyNumber = 504, CountryNumber = 504 },
            new CountryCurrency() { Country = "Mozambique", CurrencyName = "Mozambique Metical", CurrencyCode = "MZN", CurrencyNumber = 943, CountryNumber = 508 },
            new CountryCurrency() { Country = "Myanmar", CurrencyName = "Kyat", CurrencyCode = "MMK", CurrencyNumber = 104, CountryNumber = 104 },
            new CountryCurrency() { Country = "Namibia", CurrencyName = "Namibia Dollar", CurrencyCode = "NAD", CurrencyNumber = 516, CountryNumber = 516 },
            new CountryCurrency() { Country = "Namibia", CurrencyName = "Rand", CurrencyCode = "ZAR", CurrencyNumber = 710, CountryNumber = 516 },
            new CountryCurrency() { Country = "Nauru", CurrencyName = "Australian Dollar", CurrencyCode = "AUD", CurrencyNumber = 36, CountryNumber = 520 },
            new CountryCurrency() { Country = "Nepal", CurrencyName = "Nepalese Rupee", CurrencyCode = "NPR", CurrencyNumber = 524, CountryNumber = 524 },
            new CountryCurrency() { Country = "Netherlands (The)", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 528 },
            new CountryCurrency() { Country = "New Caledonia", CurrencyName = "CFP Franc", CurrencyCode = "XPF", CurrencyNumber = 953, CountryNumber = 540 },
            new CountryCurrency() { Country = "New Zealand", CurrencyName = "New Zealand Dollar", CurrencyCode = "NZD", CurrencyNumber = 554, CountryNumber = 554 },
            new CountryCurrency() { Country = "Nicaragua", CurrencyName = "Cordoba Oro", CurrencyCode = "NIO", CurrencyNumber = 558, CountryNumber = 558 },
            new CountryCurrency() { Country = "Niger (The)", CurrencyName = "CFA Franc BCEAO", CurrencyCode = "XOF", CurrencyNumber = 952, CountryNumber = 562 },
            new CountryCurrency() { Country = "Nigeria", CurrencyName = "Naira", CurrencyCode = "NGN", CurrencyNumber = 566, CountryNumber = 566 },
            new CountryCurrency() { Country = "Niue", CurrencyName = "New Zealand Dollar", CurrencyCode = "NZD", CurrencyNumber = 554, CountryNumber = 570 },
            new CountryCurrency() { Country = "Norfolk Island", CurrencyName = "Australian Dollar", CurrencyCode = "AUD", CurrencyNumber = 36, CountryNumber = 574 },
            new CountryCurrency() { Country = "Northern Mariana Islands (The)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 580 },
            new CountryCurrency() { Country = "Norway", CurrencyName = "Norwegian Krone", CurrencyCode = "NOK", CurrencyNumber = 578, CountryNumber = 578 },
            new CountryCurrency() { Country = "Oman", CurrencyName = "Rial Omani", CurrencyCode = "OMR", CurrencyNumber = 512, CountryNumber = 512 },
            new CountryCurrency() { Country = "Pakistan", CurrencyName = "Pakistan Rupee", CurrencyCode = "PKR", CurrencyNumber = 586, CountryNumber = 586 },
            new CountryCurrency() { Country = "Palau", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 585 },
            new CountryCurrency() { Country = "Panama", CurrencyName = "Balboa", CurrencyCode = "PAB", CurrencyNumber = 590, CountryNumber = 591 },
            new CountryCurrency() { Country = "Panama", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 591 },
            new CountryCurrency() { Country = "Papua New Guinea", CurrencyName = "Kina", CurrencyCode = "PGK", CurrencyNumber = 598, CountryNumber = 598 },
            new CountryCurrency() { Country = "Paraguay", CurrencyName = "Guarani", CurrencyCode = "PYG", CurrencyNumber = 600, CountryNumber = 600 },
            new CountryCurrency() { Country = "Peru", CurrencyName = "Nuevo Sol", CurrencyCode = "PEN", CurrencyNumber = 604, CountryNumber = 604 },
            new CountryCurrency() { Country = "Philippines (The)", CurrencyName = "Philippine Peso", CurrencyCode = "PHP", CurrencyNumber = 608, CountryNumber = 608 },
            new CountryCurrency() { Country = "Pitcairn", CurrencyName = "New Zealand Dollar", CurrencyCode = "NZD", CurrencyNumber = 554, CountryNumber = 612 },
            new CountryCurrency() { Country = "Poland", CurrencyName = "Zloty", CurrencyCode = "PLN", CurrencyNumber = 985, CountryNumber = 616 },
            new CountryCurrency() { Country = "Portugal", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 620 },
            new CountryCurrency() { Country = "Puerto Rico", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 630 },
            new CountryCurrency() { Country = "Qatar", CurrencyName = "Qatari Rial", CurrencyCode = "QAR", CurrencyNumber = 634, CountryNumber = 634 },
            new CountryCurrency() { Country = "Republic Of North Macedonia", CurrencyName = "Denar", CurrencyCode = "MKD", CurrencyNumber = 807, CountryNumber = 807 },
            new CountryCurrency() { Country = "Romania", CurrencyName = "Romanian Leu", CurrencyCode = "RON", CurrencyNumber = 946, CountryNumber = 642 },
            new CountryCurrency() { Country = "Russian Federation (The)", CurrencyName = "Russian Ruble", CurrencyCode = "RUB", CurrencyNumber = 643, CountryNumber = 643 },
            new CountryCurrency() { Country = "Rwanda", CurrencyName = "Rwanda Franc", CurrencyCode = "RWF", CurrencyNumber = 646, CountryNumber = 646 },
            new CountryCurrency() { Country = "Réunion", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 638 },
            new CountryCurrency() { Country = "Saint Barthélemy", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 652 },
            new CountryCurrency() { Country = "Saint Helena, Ascension And Tristan Da Cunha", CurrencyName = "Saint Helena Pound", CurrencyCode = "SHP", CurrencyNumber = 654, CountryNumber = 654 },
            new CountryCurrency() { Country = "Saint Kitts And Nevis", CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", CurrencyNumber = 951, CountryNumber = 659 },
            new CountryCurrency() { Country = "Saint Lucia", CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", CurrencyNumber = 951, CountryNumber = 662 },
            new CountryCurrency() { Country = "Saint Martin (French Part)", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 663 },
            new CountryCurrency() { Country = "Saint Pierre And Miquelon", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 666 },
            new CountryCurrency() { Country = "Saint Vincent And The Grenadines", CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", CurrencyNumber = 951, CountryNumber = 670 },
            new CountryCurrency() { Country = "Samoa", CurrencyName = "Tala", CurrencyCode = "WST", CurrencyNumber = 882, CountryNumber = 882 },
            new CountryCurrency() { Country = "San Marino", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 674 },
            new CountryCurrency() { Country = "Sao Tome And Principe", CurrencyName = "Dobra", CurrencyCode = "STN", CurrencyNumber = 930, CountryNumber = 678 },
            new CountryCurrency() { Country = "Saudi Arabia", CurrencyName = "Saudi Riyal", CurrencyCode = "SAR", CurrencyNumber = 682, CountryNumber = 682 },
            new CountryCurrency() { Country = "Senegal", CurrencyName = "CFA Franc BCEAO", CurrencyCode = "XOF", CurrencyNumber = 952, CountryNumber = 686 },
            new CountryCurrency() { Country = "Serbia", CurrencyName = "Serbian Dinar", CurrencyCode = "RSD", CurrencyNumber = 941, CountryNumber = 688 },
            new CountryCurrency() { Country = "Seychelles", CurrencyName = "Seychelles Rupee", CurrencyCode = "SCR", CurrencyNumber = 690, CountryNumber = 690 },
            new CountryCurrency() { Country = "Sierra Leone", CurrencyName = "Leone", CurrencyCode = "SLL", CurrencyNumber = 694, CountryNumber = 694 },
            new CountryCurrency() { Country = "Singapore", CurrencyName = "Singapore Dollar", CurrencyCode = "SGD", CurrencyNumber = 702, CountryNumber = 702 },
            new CountryCurrency() { Country = "Sint Maarten (Dutch Part)", CurrencyName = "Netherlands Antillean Guilder", CurrencyCode = "ANG", CurrencyNumber = 532, CountryNumber = 534 },
            new CountryCurrency() { Country = "Sistema Unitario De Compensacion Regional De Pagos 'Sucre'", CurrencyName = "Sucre", CurrencyCode = "XSU", CurrencyNumber = 994, CountryNumber = 0 },
            new CountryCurrency() { Country = "Slovakia", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 703 },
            new CountryCurrency() { Country = "Slovenia", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 705 },
            new CountryCurrency() { Country = "Solomon Islands", CurrencyName = "Solomon Islands Dollar", CurrencyCode = "SBD", CurrencyNumber = 90, CountryNumber = 90 },
            new CountryCurrency() { Country = "Somalia", CurrencyName = "Somali Shilling", CurrencyCode = "SOS", CurrencyNumber = 706, CountryNumber = 706 },
            new CountryCurrency() { Country = "South Africa", CurrencyName = "Rand", CurrencyCode = "ZAR", CurrencyNumber = 710, CountryNumber = 710 },
            new CountryCurrency() { Country = "South Sudan", CurrencyName = "South Sudanese Pound", CurrencyCode = "SSP", CurrencyNumber = 728, CountryNumber = 728 },
            new CountryCurrency() { Country = "Spain", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 724 },
            new CountryCurrency() { Country = "Sri Lanka", CurrencyName = "Sri Lanka Rupee", CurrencyCode = "LKR", CurrencyNumber = 144, CountryNumber = 144 },
            new CountryCurrency() { Country = "Sudan (The)", CurrencyName = "Sudanese Pound", CurrencyCode = "SDG", CurrencyNumber = 938, CountryNumber = 729 },
            new CountryCurrency() { Country = "Suriname", CurrencyName = "Surinam Dollar", CurrencyCode = "SRD", CurrencyNumber = 968, CountryNumber = 740 },
            new CountryCurrency() { Country = "Svalbard And Jan Mayen", CurrencyName = "Norwegian Krone", CurrencyCode = "NOK", CurrencyNumber = 578, CountryNumber = 744 },
            new CountryCurrency() { Country = "Eswatini", CurrencyName = "Lilangeni", CurrencyCode = "SZL", CurrencyNumber = 748, CountryNumber = 748 },
            new CountryCurrency() { Country = "Sweden", CurrencyName = "Swedish Krona", CurrencyCode = "SEK", CurrencyNumber = 752, CountryNumber = 752 },
            new CountryCurrency() { Country = "Switzerland", CurrencyName = "WIR Euro", CurrencyCode = "CHE", CurrencyNumber = 947, CountryNumber = 756 },
            new CountryCurrency() { Country = "Switzerland", CurrencyName = "Swiss Franc", CurrencyCode = "CHF", CurrencyNumber = 756, CountryNumber = 756 },
            new CountryCurrency() { Country = "Switzerland", CurrencyName = "WIR Franc", CurrencyCode = "CHW", CurrencyNumber = 948, CountryNumber = 756 },
            new CountryCurrency() { Country = "Syrian Arab Republic (the)", CurrencyName = "Syrian Pound", CurrencyCode = "SYP", CurrencyNumber = 760, CountryNumber = 760 },
            new CountryCurrency() { Country = "Taiwan (Province Of China)", CurrencyName = "New Taiwan Dollar", CurrencyCode = "TWD", CurrencyNumber = 901, CountryNumber = 158 },
            new CountryCurrency() { Country = "Tajikistan", CurrencyName = "Somoni", CurrencyCode = "TJS", CurrencyNumber = 972, CountryNumber = 762 },
            new CountryCurrency() { Country = "Tanzania, United Republic Of", CurrencyName = "Tanzanian Shilling", CurrencyCode = "TZS", CurrencyNumber = 834, CountryNumber = 834 },
            new CountryCurrency() { Country = "Thailand", CurrencyName = "Baht", CurrencyCode = "THB", CurrencyNumber = 764, CountryNumber = 764 },
            new CountryCurrency() { Country = "Timor-Leste", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 626 },
            new CountryCurrency() { Country = "Togo", CurrencyName = "CFA Franc BCEAO", CurrencyCode = "XOF", CurrencyNumber = 952, CountryNumber = 768 },
            new CountryCurrency() { Country = "Tokelau", CurrencyName = "New Zealand Dollar", CurrencyCode = "NZD", CurrencyNumber = 554, CountryNumber = 772 },
            new CountryCurrency() { Country = "Tonga", CurrencyName = "Pa’anga", CurrencyCode = "TOP", CurrencyNumber = 776, CountryNumber = 776 },
            new CountryCurrency() { Country = "Trinidad And Tobago", CurrencyName = "Trinidad and Tobago Dollar", CurrencyCode = "TTD", CurrencyNumber = 780, CountryNumber = 780 },
            new CountryCurrency() { Country = "Tunisia", CurrencyName = "Tunisian Dinar", CurrencyCode = "TND", CurrencyNumber = 788, CountryNumber = 788 },
            new CountryCurrency() { Country = "Turkey", CurrencyName = "Turkish Lira", CurrencyCode = "TRY", CurrencyNumber = 949, CountryNumber = 792 },
            new CountryCurrency() { Country = "Turkmenistan", CurrencyName = "Turkmenistan New Manat", CurrencyCode = "TMT", CurrencyNumber = 934, CountryNumber = 795 },
            new CountryCurrency() { Country = "Turks And Caicos Islands (The)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 796 },
            new CountryCurrency() { Country = "Tuvalu", CurrencyName = "Australian Dollar", CurrencyCode = "AUD", CurrencyNumber = 36, CountryNumber = 798 },
            new CountryCurrency() { Country = "Uganda", CurrencyName = "Uganda Shilling", CurrencyCode = "UGX", CurrencyNumber = 800, CountryNumber = 800 },
            new CountryCurrency() { Country = "Ukraine", CurrencyName = "Hryvnia", CurrencyCode = "UAH", CurrencyNumber = 980, CountryNumber = 804 },
            new CountryCurrency() { Country = "United Arab Emirates (The)", CurrencyName = "UAE Dirham", CurrencyCode = "AED", CurrencyNumber = 784, CountryNumber = 784 },
            new CountryCurrency() { Country = "United Kingdom Of Great Britain And Northern Ireland (The)", CurrencyName = "Pound Sterling", CurrencyCode = "GBP", CurrencyNumber = 826, CountryNumber = 826 },
            new CountryCurrency() { Country = "United States Minor Outlying Islands (The)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 581 },
            new CountryCurrency() { Country = "United States Of America (The)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 840 },
            new CountryCurrency() { Country = "United States Of America (The)", CurrencyName = "US Dollar (Next day)", CurrencyCode = "USN", CurrencyNumber = 997, CountryNumber = 840 },
            new CountryCurrency() { Country = "Uruguay", CurrencyName = "Uruguay Peso en Unidades Indexadas (URUIURUI)", CurrencyCode = "UYI", CurrencyNumber = 940, CountryNumber = 858 },
            new CountryCurrency() { Country = "Uruguay", CurrencyName = "Peso Uruguayo", CurrencyCode = "UYU", CurrencyNumber = 858, CountryNumber = 858 },
            new CountryCurrency() { Country = "Uzbekistan", CurrencyName = "Uzbekistan Sum", CurrencyCode = "UZS", CurrencyNumber = 860, CountryNumber = 860 },
            new CountryCurrency() { Country = "Vanuatu", CurrencyName = "Vatu", CurrencyCode = "VUV", CurrencyNumber = 548, CountryNumber = 548 },
            new CountryCurrency() { Country = "Venezuela (Bolivarian Republic Of)", CurrencyName = "Bolivar", CurrencyCode = "VEF", CurrencyNumber = 937, CountryNumber = 862 },
            new CountryCurrency() { Country = "Viet Nam", CurrencyName = "Dong", CurrencyCode = "VND", CurrencyNumber = 704, CountryNumber = 704 },
            new CountryCurrency() { Country = "Virgin Islands (British)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 92 },
            new CountryCurrency() { Country = "Virgin Islands (U.S.)", CurrencyName = "US Dollar", CurrencyCode = "USD", CurrencyNumber = 840, CountryNumber = 850 },
            new CountryCurrency() { Country = "Wallis And Futuna", CurrencyName = "CFP Franc", CurrencyCode = "XPF", CurrencyNumber = 953, CountryNumber = 876 },
            new CountryCurrency() { Country = "Western Sahara", CurrencyName = "Moroccan Dirham", CurrencyCode = "MAD", CurrencyNumber = 504, CountryNumber = 732 },
            new CountryCurrency() { Country = "Yemen", CurrencyName = "Yemeni Rial", CurrencyCode = "YER", CurrencyNumber = 886, CountryNumber = 887 },
            new CountryCurrency() { Country = "Zambia", CurrencyName = "Zambian Kwacha", CurrencyCode = "ZMW", CurrencyNumber = 967, CountryNumber = 894 },
            new CountryCurrency() { Country = "Zimbabwe", CurrencyName = "Zimbabwe Dollar", CurrencyCode = "ZWL", CurrencyNumber = 932, CountryNumber = 716 },
            new CountryCurrency() { Country = "Åland Islands", CurrencyName = "Euro", CurrencyCode = "EUR", CurrencyNumber = 978, CountryNumber = 248 },
        };
    }
}
